/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myproject.app;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        System.out.println("hello world");

    }

    public static boolean search(ArrayList<Integer> a, int b) {
        if (a == null)
            return false;
        else
            return true;
    }
}
